name       : python-sphinxcontrib-devhelp
version    : 1.0.1
release    : 1
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-devhelp/archive/1.0.1.tar.gz : d18a43cf4438339685b9e141e5aa12cde19a6c99d26dbc446c31a53ac8b1d4d2
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for Devhelp documents
description: |
    sphinxcontrib-devhelp is a sphinx extension which outputs Devhelp document.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
