name       : python-sphinxcontrib-devhelp
version    : 1.0.2
release    : 4
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-devhelp/archive/1.0.2.tar.gz : 00f9fbe1d6362764fec95f38ab105f7fea784af79d6ecf2582c4174c83131511
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for Devhelp documents
description: |
    sphinxcontrib-devhelp is a sphinx extension which outputs Devhelp document.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
